### ISSUE TITLE
XSLT fails for Abbyy output in OcrJob reingest on dea-bl01

### ISSUE THREAD

**Issue by kahlep** [Transkribus/TranskribusCore#2]
SystemId Unknown; Line #9; Column #170; "xpath-default-namespace" attribute is not allowed on the xsl:stylesheet element!
SystemId Unknown; Line #44; Column #64; Could not find function: current-dateTime
SystemId Unknown; Line #44; Column #64; function token not found.
(Location of error unknown)java.lang.NullPointerException
[ocr_ex-1] ERROR eu.transkribus.appserver.logic.jobs.abstractjobs.ATrpJobRunnable - An unexpected error occurred!
java.lang.NullPointerException
	at eu.transkribus.core.util.XslTransformer.transform(XslTransformer.java:136)
	at eu.transkribus.core.util.XslTransformer.transform(XslTransformer.java:95)
	at eu.transkribus.core.util.JaxbUtils.transformToObject(JaxbUtils.java:217)
	at eu.transkribus.core.util.PageXmlUtils.createPcGtsTypeFromAbbyy(PageXmlUtils.java:411)
	at eu.transkribus.core.io.LocalDocReader.load(LocalDocReader.java:245)
	at eu.transkribus.core.io.LocalDocReader.load(LocalDocReader.java:91)
	at eu.transkribus.appserver.logic.jobs.standard.OcrJob.doProcess(OcrJob.java:163)
	at eu.transkribus.appserver.logic.jobs.abstractjobs.ATrpJobRunnable.run(ATrpJobRunnable.java:67)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kahlep** [comment]
Saxon Transformer is explicitly created in order to make XSLT 2.0 work
